spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/userdb
    #username: root
    #password: root
    url: jdbc:h2:mem:userdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  user:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
  h2:
    console:
      enabled: true

security:
  oauth2:
    resource:
      filter-order: 3
