server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/tmp/config-git
  security:
    user:
      name: user
      password: password

management:
  security:
    enabled: false