server:
  port: 9000
#spring:
#  main:
#    web-application-type: none
  jackson:
    serialization:
      INDENT_OUTPUT: true
  liquibase:
      enabled: false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: sandbox-group-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
