spring:
  main:
    web-application-type: none
  jackson:
    serialization:
      INDENT_OUTPUT: true
  liquibase:
      enabled: false
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  bootstrapAddress: localhost:9092
message:
  topic:
    name: sandbox
stockTicker:
  topic:
    name: stockTicker
    dlt: stockTicker.deadLetterTopic
filtered:
  topic:
    name: filtered
partitioned:
  topic:
    name: partitioned