spring:
  main:
    web-application-type: none
  jackson:
    serialization:
      INDENT_OUTPUT: true
  liquibase:
      enabled: false

kafka:
  bootstrapAddress: localhost:9092
message:
  topic:
    name: sandbox
stockTicker:
  topic:
    name: stockTicker
filtered:
  topic:
    name: filtered
partitioned:
  topic:
    name: partitioned