spring:
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: jdbc:h2:mem:bankdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
        #exclude:
  security:
    enabled: false
